int SAY;
void interrupt(){
SAY++;
PORTC=Dec2Bcd(SAY);
INTCON.INTF=0; // KESME BAYRAÐI SIFIRLAMAK YENÝDEN KESME MÜMKÜN KILAR
}
void main() {
ANSEL=ANSELH=0;
TRISC=0X00;
TRISB=0XFF;
INTCON.GIE=1; //GLOBAL KESMELERE ÝZÝN VER
INTCON.INTE=1;// RB0 KESMESÝNE ÝZÝN VER
//INTCON=0B10010000;
OPTION_REG.INTEDG=1;// ÜRETÝLEN KARE DALGANIN YÜKSELEN KENARINDAN
PORTC=0;
while(PORTB.b0=1){

}

}